# The weather Dataset project

Summary:
    In this project we see the wheather condition at perticular location . we see Temprature , Temprature Dew point, 
    Relative Humidity, Wind speed, Visiblity, pressure and conditions with the help of pandas DataFrame

In [173]:
import io
%cd "C:\Users\dafiy\OneDrive\Desktop\Dafiya\Data Analytics\Projects\wheather"

C:\Users\dafiy\OneDrive\Desktop\Dafiya\Data Analytics\Projects\wheather

In [174]:
import pandas as pd
wd=pd.read_csv("weather.csv")

# Analyzing DataFrames

In [175]:
wd.head(10)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No

In [176]:
wd.tail(10)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
356,3.4,15.0,0.8,4.8,11.7,S,70.0,S,S,35.0,...,24,1023.4,1023.1,1,5,8.3,14.3,No,0.0,No
357,3.2,18.0,0.0,7.4,12.2,SSE,48.0,SSE,S,26.0,...,25,1026.6,1022.8,1,2,9.1,16.3,No,0.0,No
358,0.9,20.7,0.0,5.4,8.4,NNW,39.0,SSE,N,2.0,...,29,1023.2,1018.4,3,8,9.4,19.1,No,0.0,No
359,3.3,25.5,0.0,5.2,10.8,N,43.0,N,NNW,4.0,...,16,1018.8,1014.6,0,3,12.0,24.8,No,0.0,No
360,7.9,26.1,0.0,6.8,3.5,NNW,43.0,NaN,WNW,0.0,...,20,1017.6,1014.2,5,8,16.3,25.9,No,0.0,No
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

In [177]:
wd.shape  #it shows total number of rows and columns in the data

(366, 22)

In [178]:
#we will see the index of this data
wd.index

#so the starting index is 0 and last index is 366

RangeIndex(start=0, stop=366, step=1)

In [179]:
wd.columns  #with this help of command we sill see the column names

Index(['MinTemp', 'MaxTemp', 'Rainfall', 'Evaporation', 'Sunshine',
       'WindGustDir', 'WindGustSpeed', 'WindDir9am', 'WindDir3pm',
       'WindSpeed9am', 'WindSpeed3pm', 'Humidity9am', 'Humidity3pm',
       'Pressure9am', 'Pressure3pm', 'Cloud9am', 'Cloud3pm', 'Temp9am',
       'Temp3pm', 'RainToday', 'RISK_MM', 'RainTomorrow'],
      dtype='object')

In [180]:
wd.dtypes  #if we want to see what type of data we used in the existing data then we used dtypes command

MinTemp          float64
MaxTemp          float64
Rainfall         float64
Evaporation      float64
Sunshine         float64
WindGustDir       object
WindGustSpeed    float64
WindDir9am        object
WindDir3pm        object
WindSpeed9am     float64
WindSpeed3pm       int64
Humidity9am        int64
Humidity3pm        int64
Pressure9am      float64
Pressure3pm      float64
Cloud9am           int64
Cloud3pm           int64
Temp9am          float64
Temp3pm          float64
RainToday         object
RISK_MM          float64
RainTomorrow      object
dtype: object

In [181]:
wd['MinTemp'].unique()   #if we wants to check the unique values on single column not on whole frame then

array([ 8. , 14. , 13.7, 13.3,  7.6,  6.2,  6.1,  8.3,  8.8,  8.4,  9.1,
        8.5, 10.1, 12.1, 12.4, 13.8, 11.7, 15.6, 15.3, 16.4, 12.8, 12. ,
       15.4, 12.9, 15.1, 13.6, 11.6, 16.6, 14.5, 16.3, 17.2, 16.5, 15. ,
       14.9, 11.8,  9.6,  8.9, 15.5, 10.8,  7.5, 12.6, 14.8, 19.9,  9.2,
       11.3,  9.8, 14.3, 14.4, 15.9, 16.7, 17.5, 14.7, 20.9, 17. , 16. ,
       17.9, 15.2, 10. ,  9.9, 10.3, 12.7, 13.2, 18. , 17.6, 17.1, 18.2,
       16.8, 10.4,  8.6, 11.2, 11.4, 11.5, 13. ,  7.7,  4.4,  7.4,  9.5,
       12.5, 13.9, 12.3, 13.1,  7.1,  4.2,  3.5,  5.3,  7. ,  0.4,  3.2,
        5.9,  8.1,  6.9,  5.6,  7.2,  5.4,  6.3,  7.9,  2.4,  2.5,  5. ,
        3.8,  4.3, -2.1, -1.8,  2.1,  0.5, -0.9, -0.2,  0.1,  1.5,  9.4,
        1.3,  2.2, -0.4,  4.5, -2.7,  0.3,  1.2, -0.3,  4.7,  4.9,  1.4,
       -0.1,  0.6,  4.6, 10.6,  7.8, 10.2,  7.3,  8.7,  1. ,  6.4,  4. ,
        0.9,  0.8, -1.5,  6.6, -1.6, -3.1, -0.6,  3. ,  2.9, -1.3,  1.8,
       -2.6,  2.7, -1.7, -1.1,  2.3, -2.2, -3.5, -1. , -2. , -2.3, -2.8,
       -1.9,  4.8,  3.1, -2.9,  3.7, -3.4, -5.3,  0. , -3.7, -3.3,  4.1,
        5.8,  0.2, -2.5, -0.5,  9. ,  3.9,  0.7,  1.1,  5.1,  6.5,  8.2,
        6.7, 11.9,  3.4,  3.3])

In [182]:
#Total no of unique values in each column.we can used both for single column or for whole dataframe
#--> we have applied for whole DataFrame
wd.nunique()

MinTemp          180
MaxTemp          187
Rainfall          47
Evaporation       55
Sunshine         114
WindGustDir       16
WindGustSpeed     35
WindDir9am        16
WindDir3pm        16
WindSpeed9am      22
WindSpeed3pm      26
Humidity9am       60
Humidity3pm       74
Pressure9am      190
Pressure3pm      193
Cloud9am           9
Cloud3pm           9
Temp9am          178
Temp3pm          200
RainToday          2
RISK_MM           47
RainTomorrow       2
dtype: int64

In [183]:
wd['MaxTemp'].nunique()  #if we want to see the total number of unique values on maxTemp column

187

In [184]:
wd['MaxTemp'].count()  #here it will shows the total number of non-null values in MaxTemp.
#we can use count for single columns as well as for whole Dataframe

366

In [185]:
wd.count()  #here we will see the total number of non-null values for whole frame

MinTemp          366
MaxTemp          366
Rainfall         366
Evaporation      366
Sunshine         363
WindGustDir      363
WindGustSpeed    364
WindDir9am       335
WindDir3pm       365
WindSpeed9am     359
WindSpeed3pm     366
Humidity9am      366
Humidity3pm      366
Pressure9am      366
Pressure3pm      366
Cloud9am         366
Cloud3pm         366
Temp9am          366
Temp3pm          366
RainToday        366
RISK_MM          366
RainTomorrow     366
dtype: int64

In [186]:
wd['Sunshine'].value_counts()
#this value_count shows all the unique values with count as you can see at last there are 114 unique value are there 
#it is note that it works only on single column not on whole DataFrame

Sunshine
0.0     10
8.4      8
8.1      8
8.9      8
5.6      7
        ..
0.1      1
13.5     1
6.9      1
13.3     1
5.3      1
Name: count, Length: 114, dtype: int64

In [187]:
wd.info()  #here you can see the total information of the existing dataframe such as column name calues and datatypes ,index range

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 366 entries, 0 to 365
Data columns (total 22 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   MinTemp        366 non-null    float64
 1   MaxTemp        366 non-null    float64
 2   Rainfall       366 non-null    float64
 3   Evaporation    366 non-null    float64
 4   Sunshine       363 non-null    float64
 5   WindGustDir    363 non-null    object
 6   WindGustSpeed  364 non-null    float64
 7   WindDir9am     335 non-null    object
 8   WindDir3pm     365 non-null    object
 9   WindSpeed9am   359 non-null    float64
 10  WindSpeed3pm   366 non-null    int64
 11  Humidity9am    366 non-null    int64
 12  Humidity3pm    366 non-null    int64
 13  Pressure9am    366 non-null    float64
 14  Pressure3pm    366 non-null    float64
 15  Cloud9am       366 non-null    int64
 16  Cloud3pm       366 non-null    int64
 17  Temp9am        366 non-null    float64
 18  Temp3pm        366 non-null    float64
 19  RainToday      366 non-null    object
 20  RISK_MM        366 non-null    float64
 21  RainTomorrow   366 non-null    object
dtypes: float64(12), int64(5), object(5)
memory usage: 63.0+ KB

# Now we will perform some operations on this dataframe

1.Find all the unique 'Wind Speed' at 3pm, values in the data.

In [188]:
#here all the unique values in windspeed 3pm
all_unique=wd['WindSpeed3pm'].unique()
print(all_unique)
#we will see how much unique value present at windspeed
total_uniq=wd['WindSpeed3pm'].nunique()
print("total unique value of windspeed at 3pm is: ", total_uniq)

[20 17  6 24 28 26  9 15  7 19 11 13 31 22 35 30 48  4 37 33  0  2 39 52
 41 50]
total unique value of windspeed at 3pm is:  26

# Filtering

In [189]:
wd.head(10)

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No

In [190]:
wd[wd.RainToday == 'No'] #it will filter only those columns in which there is no rain

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

# groupby()

In [191]:
#same filtering by using group by but now will take raining today should be yes
wd.groupby('RainToday').get_group('Yes')

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunshine,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,7.8,16.2,17.4,6.4,7.9,NW,50.0,NW,N,15.0,...,44,1016.7,1017.8,7,1,8.0,14.3,Yes,0.0,No
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
339,10.3,21.3,3.0,4.2,6.7,NNW,43.0,ENE,N,7.0,...,46,1018.1,1013.6,8,1,11.7,19.8,Yes,0.0,No
341,0.3,16.0,8.2,5.4,11.8,NW,57.0,NNW,N,11.0,...,45,1016.8,1013.3,1,1,6.9,14.6,Yes,0.0,No
348,11.9,21.1,13.2,6.6,NaN,NW,41.0,NNE,N,7.0,...,61,1019.2,1016.7,7,3,14.5,19.4,Yes,0.6,No

3) Find the number of times when the 'Wind Speed at 9 was exactly 4 km/h'.

In [235]:
wd[wd.WindSpeed9am == 4.0]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunlight,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
18,12.4,32.3,0.6,7.4,13.0,E,39.0,NNE,W,4.0,...,25,1017.1,1013.3,1,3,20.2,31.2,No,0.0,No
49,12.6,23.1,3.4,1.6,2.3,NNW,30.0,N,NW,4.0,...,74,1015.8,1014.1,8,7,15.3,20.4,Yes,6.4,Yes
72,20.9,35.7,0.0,13.8,6.9,SW,50.0,E,WNW,4.0,...,28,1007.6,1003.0,7,2,23.6,34.0,No,2.0,Yes
86,12.7,28.8,0.0,7.4,9.0,NNE,28.0,NW,SSW,4.0,...,28,1016.5,1012.4,1,5,18.3,28.3,No,0.0,No
87,13.2,31.3,0.0,6.6,11.6,WSW,46.0,N,WNW,4.0,...,28,1013.1,1009.5,1,4,19.7,30.7,No,0.0,No
88,15.3,33.2,0.0,9.4,13.2,NNW,44.0,NNE,NW,4.0,...,18,1013.9,1012.0,0,1,22.4,32.1,No,0.0,No
112,16.3,24.8,1.8,7.8,3.8,S,50.0,NNW,N,4.0,...,56,1011.8,1008.4,7,7,17.5,24.0,Yes,6.6,Yes
117,13.0,28.2,0.0,5.0,11.6,NW,44.0,WSW,NW,4.0,...,27,1017.6,1014.4,3,6,17.4,27.0,No,0.0,No
136,11.3,32.3,0.0,9.4,11.4,NE,28.0,ENE,WNW,4.0,...,17,1024.3,1020.7,5,2,18.2,30.5,No,0.0,No
139,15.1,26.2,0.0,9.0,9.8,NE,31.0,SE,NNE,4.0,...,48,1022.1,1018.7,1,4,19.7,24.5,No,0.0,No
161,7.2,22.9,0.0,2.2,9.5,E,26.0,NNW,N,4.0,...,28,1023.1,1019.2,1,1,14.0,22.2,No,0.0,No
193,9.4,19.2,0.0,2.2,7.7,NaN,24.0,E,NNW,4.0,...,47,1024.2,1020.3,7,1,12.1,18.8,No,0.0,No
219,-0.2,15.5,0.0,1.4,9.0,NE,28.0,N,ESE,4.0,...,42,1027.6,1027.0,1,1,4.9,14.5,No,0.0,No
246,-3.1,12.0,0.0,1.8,3.9,ESE,35.0,SSW,NE,4.0,...,52,1030.5,1030.0,1,6,5.9,10.2,No,0.0,No
276,2.3,12.8,0.0,2.2,9.6,WNW,35.0,ENE,WNW,4.0,...,48,1021.2,1018.1,1,1,7.8,11.6,No,0.0,No
277,-2.0,12.3,0.0,2.4,5.8,W,31.0,ESE,W,4.0,...,60,1020.9,1018.3,1,7,2.6,9.1,No,0.0,No
292,-5.3,13.1,0.0,2.2,7.9,NW,33.0,N,NNW,4.0,...,47,1029.6,1025.6,6,6,0.1,12.2,No,0.0,No
303,0.5,16.3,0.0,1.8,4.1,NNW,39.0,SSW,WSW,4.0,...,45,1023.7,1017.5,7,8,6.2,15.4,No,4.0,Yes
315,-2.5,16.6,0.0,3.0,9.9,NW,31.0,NE,N,4.0,...,20,1018.8,1013.9,1,1,6.0,16.3,No,0.0,No
328,2.4,17.3,0.0,2.2,11.3,E,31.0,SSE,SW,4.0,...,33,1030.5,1027.7,1,1,10.7,16.5,No,0.0,No
329,3.2,18.7,0.0,2.6,11.1,N,31.0,E,NNW,4.0,...,32,1032.2,1026.9,1,1,11.0,18.1,No,0.0,No
346,4.5,23.9,0.0,4.8,11.7,NW,30.0,ENE,NNW,4.0,...,27,1025.8,1021.5,0,4,12.6,22.3,No,0.0,No
349,9.2,19.6,0.6,3.4,10.4,ENE,31.0,SSE,NNW,4.0,...,42,1022.3,1019.7,7,4,11.6,18.4,No,0.0,No
352,6.7,24.7,0.0,5.4,8.6,NW,43.0,N,NW,4.0,...,31,1025.7,1022.2,1,7,12.7,23.7,No,0.0,No
359,3.3,25.5,0.0,5.2,10.8,N,43.0,N,NNW,4.0,...,16,1018.8,1014.6,0,3,12.0,24.8,No,0.0,No

 4) Find out all the Null Values in the data.

In [193]:
wd.isnull().sum()  #it will show the total not null values of each columns

MinTemp           0
MaxTemp           0
Rainfall          0
Evaporation       0
Sunshine          3
WindGustDir       3
WindGustSpeed     2
WindDir9am       31
WindDir3pm        1
WindSpeed9am      7
WindSpeed3pm      0
Humidity9am       0
Humidity3pm       0
Pressure9am       0
Pressure3pm       0
Cloud9am          0
Cloud3pm          0
Temp9am           0
Temp3pm           0
RainToday         0
RISK_MM           0
RainTomorrow      0
dtype: int64

In [194]:
#another function to check null values
wd.notnull().sum()  #there is no null value in whole data

MinTemp          366
MaxTemp          366
Rainfall         366
Evaporation      366
Sunshine         363
WindGustDir      363
WindGustSpeed    364
WindDir9am       335
WindDir3pm       365
WindSpeed9am     359
WindSpeed3pm     366
Humidity9am      366
Humidity3pm      366
Pressure9am      366
Pressure3pm      366
Cloud9am         366
Cloud3pm         366
Temp9am          366
Temp3pm          366
RainToday        366
RISK_MM          366
RainTomorrow     366
dtype: int64

4) Rename the column name 'Sunshine' of the dataframe to 'sunlight'.

In [195]:
wd.rename(columns = {'Sunshine' :'Sunlight'},inplace=True)

In [196]:
wd.head()

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunlight,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
0,8.0,24.3,0.0,3.4,6.3,NW,30.0,SW,NW,6.0,...,29,1019.7,1015.0,7,7,14.4,23.6,No,3.6,Yes
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No

5)  What is the mean 'Humidity3pm' ,'MinTemp','MaxTemp' ?

In [197]:
Humid_mean=wd.Humidity3pm.mean()
print("The Average Humdity at 3pm is: ",Humid_mean)
print()
maxTemp_mean=wd.MaxTemp.mean()
print("The Average of maximum Temprature is: ",maxTemp_mean)
print()
minTemp_mean=wd.MinTemp.mean()
print("The Average of Minimum Temprature is: ",minTemp_mean)
print()

The Average Humdity at 3pm is:  44.51912568306011

The Average of maximum Temprature is:  20.550273224043714

The Average of Minimum Temprature is:  7.265573770491804

6) What is the Standard Deviation of 'Rainfall'  in this data?

In [198]:
wd.Rainfall.std()

4.225799585804068

7) What is the Variance of 'WindSpeed9am' in this data ?

In [199]:
wd.WindSpeed9am.var()

63.23317408692683

In [200]:
wd['WindSpeed9am'].var()  #another way to find variance its just another pattern

63.23317408692683

8) Find all instances when Risk is high.

In [201]:
wd[wd.RISK_MM>=15]  #filtering

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunlight,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
8,8.8,19.5,0.0,4.0,4.1,S,48.0,E,ENE,19.0,...,48,1026.1,1022.7,7,7,14.1,18.9,No,16.2,Yes
21,16.4,19.4,0.4,9.2,0.0,E,26.0,ENE,E,6.0,...,72,1010.7,1008.9,8,8,16.5,18.3,No,25.8,Yes
29,13.6,24.1,0.4,2.6,0.5,NNW,30.0,SSW,S,6.0,...,49,1017.2,1013.3,8,7,17.3,23.2,No,22.6,Yes
51,19.9,22.0,11.0,4.4,5.9,NNW,76.0,N,WNW,41.0,...,62,996.5,996.8,8,3,20.6,19.6,Yes,17.4,Yes
78,15.1,20.4,0.0,9.6,0.1,ESE,39.0,ESE,ESE,17.0,...,55,1017.5,1015.8,8,8,17.8,19.4,No,18.8,Yes
98,14.5,24.2,0.0,6.8,5.9,SSW,61.0,N,NNW,11.0,...,76,999.4,998.9,7,7,17.9,20.3,No,16.2,Yes
145,13.1,17.4,6.4,2.8,0.0,NNW,43.0,N,N,11.0,...,93,1010.2,1006.5,8,8,16.4,16.6,Yes,19.8,Yes
249,3.0,11.1,0.8,1.4,0.2,W,35.0,NaN,N,0.0,...,96,1024.4,1021.1,7,8,6.3,8.6,No,16.8,Yes
262,-1.1,11.0,0.2,1.8,0.0,WNW,41.0,NaN,NE,0.0,...,87,1014.4,1009.0,7,8,2.4,8.7,No,19.2,Yes
326,3.2,21.9,0.0,6.8,5.2,NW,80.0,SSE,NW,2.0,...,50,1012.1,1006.5,1,8,15.9,21.0,No,17.4,Yes

8) Find all instances of no rain tomorrow.

In [202]:
wd[wd['RainTomorrow'].str.contains('No')]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunlight,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
5,6.2,16.9,0.0,5.8,8.2,SE,44.0,SE,E,20.0,...,57,1023.8,1021.7,7,5,10.9,14.8,No,0.2,No
6,6.1,18.2,0.2,4.2,8.4,SE,43.0,SE,ESE,19.0,...,47,1024.6,1022.2,4,6,12.4,17.3,No,0.0,No
7,8.3,17.0,0.0,5.6,4.6,E,41.0,SE,E,11.0,...,57,1026.2,1024.2,6,7,12.1,15.5,No,0.0,No
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
363,12.5,19.9,0.0,8.4,5.3,ESE,43.0,ENE,ENE,11.0,...,47,1024.0,1022.8,3,2,14.5,18.3,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No

9) Find all the instances when minimum Temprature is above 11 and Sunlight is 6

In [203]:
wd[(wd['MinTemp']>11) & (wd['Sunlight']==6)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunlight,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
74,16.0,22.8,0.0,12.4,6.0,E,50.0,E,ENE,13.0,...,57,1012.3,1012.3,8,6,17.0,21.6,No,0.0,No
318,13.1,19.4,9.8,8.8,6.0,NNW,67.0,N,NW,39.0,...,43,1007.3,1006.0,7,1,16.7,18.2,Yes,1.6,Yes

10) What is the Mean value of each column against each 'Pressure3pm ?

In [217]:
wd['Pressure3pm'].mean()

1016.8103825136611

10) Minimum and maxium wind speed and also find min and maximum temprratue at morning

In [234]:
wind_speed_max=wd['WindGustSpeed'].max()
print("maximum wind speed is: ",wind_speed_max)
print()
wind_speed_min=wd['WindGustSpeed'].min()
print("minimum wind speed is: ",wind_speed_min)
print()

print("***Max and min Temprature****")
max_temp=wd['Temp9am'].max()
print("maximum Temprature in morning is: ",max_temp)
print()
min_temp=wd['Temp9am'].min()
print("minimum Temprature in morning is: ",min_temp)
print()

maximum wind speed is:  98.0

minimum wind speed is:  13.0

***Max and min Temprature****
maximum Temprature in morning is:  24.7

minimum Temprature in morning is:  0.1

11) Find all the records where wind direction at 3 is South west

In [238]:
wd[wd['WindDir3pm']=='SW']

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunlight,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
31,11.6,26.3,4.2,1.6,12.0,NNE,41.0,E,SW,6.0,...,46,1013.9,1009.5,2,2,16.7,25.2,Yes,0.2,No
143,12.8,24.9,0.0,2.4,6.2,ENE,30.0,NNW,SW,6.0,...,44,1023.2,1019.3,7,6,15.5,24.2,No,0.6,No
328,2.4,17.3,0.0,2.2,11.3,E,31.0,SSE,SW,4.0,...,33,1030.5,1027.7,1,1,10.7,16.5,No,0.0,No
355,9.0,20.6,0.0,9.0,6.2,ENE,39.0,S,SW,11.0,...,28,1022.3,1018.6,7,5,11.4,18.5,No,0.8,No

12) find all the instances when there is raining or pressure at morning is above 1050

In [242]:
wd[(wd['RainToday']=='Yes') | (wd['Pressure9am']>1050)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunlight,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
3,13.3,15.5,39.8,7.2,9.1,NW,54.0,WNW,W,30.0,...,56,1005.5,1007.0,2,7,13.5,14.1,Yes,2.8,Yes
4,7.6,16.1,2.8,5.6,10.6,SSE,50.0,SSE,ESE,20.0,...,49,1018.3,1018.5,7,7,11.1,15.4,Yes,0.0,No
9,8.4,22.8,16.2,5.4,7.7,E,31.0,S,ESE,7.0,...,32,1024.1,1020.7,7,1,13.3,21.7,Yes,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
327,7.8,16.2,17.4,6.4,7.9,NW,50.0,NW,N,15.0,...,44,1016.7,1017.8,7,1,8.0,14.3,Yes,0.0,No
338,14.4,20.7,7.6,9.4,4.9,NNW,33.0,NNW,NNW,20.0,...,65,1015.5,1013.2,8,4,14.5,19.3,Yes,3.0,Yes
339,10.3,21.3,3.0,4.2,6.7,NNW,43.0,ENE,N,7.0,...,46,1018.1,1013.6,8,1,11.7,19.8,Yes,0.0,No
341,0.3,16.0,8.2,5.4,11.8,NW,57.0,NNW,N,11.0,...,45,1016.8,1013.3,1,1,6.9,14.6,Yes,0.0,No
348,11.9,21.1,13.2,6.6,NaN,NW,41.0,NNE,N,7.0,...,61,1019.2,1016.7,7,3,14.5,19.4,Yes,0.6,No

13) find all the instances when:
    a- its raining and wind speed is greater than 50
    or 
    b-Temprature at 3 is above 11

In [251]:
wd[(wd['RainToday']=='Yes') & (wd['WindGustSpeed']>70) | (wd['Temp3pm']>25)]

,MinTemp,MaxTemp,Rainfall,Evaporation,Sunlight,WindGustDir,WindGustSpeed,WindDir9am,WindDir3pm,WindSpeed9am,...,Humidity3pm,Pressure9am,Pressure3pm,Cloud9am,Cloud3pm,Temp9am,Temp3pm,RainToday,RISK_MM,RainTomorrow
1,14.0,26.9,3.6,4.4,9.7,ENE,39.0,E,W,4.0,...,36,1012.4,1008.4,5,3,17.5,25.7,Yes,3.6,Yes
2,13.7,23.4,3.6,5.8,3.3,NW,85.0,N,NNE,6.0,...,69,1009.5,1007.2,8,7,15.4,20.2,Yes,39.8,Yes
11,8.5,27.3,0.2,7.2,12.5,E,41.0,E,NW,2.0,...,35,1023.8,1019.9,0,3,16.8,26.0,No,0.0,No
12,10.1,27.9,0.0,7.2,13.0,WNW,30.0,S,NW,6.0,...,29,1022.0,1017.1,0,1,17.0,27.1,No,0.0,No
13,12.1,30.9,0.0,6.2,12.4,NW,44.0,WNW,W,7.0,...,20,1017.3,1013.1,1,4,19.7,30.7,No,0.0,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
360,7.9,26.1,0.0,6.8,3.5,NNW,43.0,NaN,WNW,0.0,...,20,1017.6,1014.2,5,8,16.3,25.9,No,0.0,No
361,9.0,30.7,0.0,7.6,12.1,NNW,76.0,SSE,NW,7.0,...,15,1016.1,1010.8,1,3,20.4,30.0,No,0.0,No
362,7.1,28.4,0.0,11.6,12.7,N,48.0,NNW,NNW,2.0,...,22,1020.0,1016.9,0,1,17.2,28.2,No,0.0,No
364,12.5,26.9,0.0,5.0,7.1,NW,46.0,SSW,WNW,6.0,...,39,1021.0,1016.2,6,7,15.8,25.9,No,0.0,No
365,12.3,30.2,0.0,6.0,12.6,NW,78.0,NW,WNW,31.0,...,13,1009.6,1009.2,1,1,23.8,28.6,No,0.0,No